
DROP TABLE IF EXISTS vehicle_errors;
DROP TABLE IF EXISTS vehicles;


CREATE TABLE vehicle_errors (
    ID INT NOT NULL PRIMARY KEY,
    VEHICLE_ID INT NOT NULL,
    ERROR_CODE INT NOT NULL,
    ERROR_MESSAGE VARCHAR(255) NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
